Reactivate Sassdoc
axa-group/web-toolkit pull request #28
Opened 2016-10-31 08:26 UTC by davidknezic

This reintroduces SassDoc, after the fix of interpolated selectors.

![screen shot 2016-10-31 at 09 18 31](https://cloud.githubusercontent.com/assets/198988/19848027/079d4cb4-9f4b-11e6-982c-d89515e25c73.png)

However, our API section currently looks very chaotic and isn't probably easy to use as a developer reference.

How about we display the items *Classes*, *CSS Utilities*, *Mixins* and *jQuery Plugins* under the *API* menu item? Then each of these items is a very long page containing all of the corresponding docs. This allows for a quick search using the browser-search.

2016-10-31 10:45 UTC, elessar-ch commented
We could even put all the classes utilities and so on into one page. Might be a bit long though.
A page-navigation with anchors might be good in either case.

2016-10-31 11:22 UTC, davidknezic commented
@elessar-ch do you have any clue, why the example doesn't get rendered properly in the image above? Also, is it normal that there's that weird indentation in the source code?

2016-10-31 12:05 UTC, FKSI commented
+1 with @elessar-ch I'd love to have all utilities on a single page even thought it might be a little long.

2016-11-02 07:03 UTC, davidknezic commented
Related https://github.com/SassDoc/scss-comment-parser/pull/25

2016-11-03 15:03 UTC, davidknezic commented
Ready to review. I think the fix for SassDoc can be done at a later point, I'll add an issue.

2016-11-03 15:04 UTC, davidknezic commented
This pr also remove a LOT of old code for pug and markdown parsing. There were also lots of unneeded dependencies.

2016-11-03 15:04 UTC, FKSI commented on lib/build-docs.js
>      console.log((new Date()).toLocaleTimeString(), 'Failed!', err)
How about switching to console.err() aren't they made for that?

2016-11-03 15:13 UTC, FKSI requested changes
Try faster

2016-11-03 15:13 UTC, FKSI approved these changes

2016-11-03 15:18 UTC, merged