Feature/phantom screenshots
axa-group/web-toolkit pull request #46
Opened 2016-11-07 17:22 UTC by elessar-ch

This PR includes everything needed to create and compare screenshots during the build.
The process is executed in a secondary rancher-container.

2016-11-08 09:25 UTC, davidknezic requested changes
See comments. Also, we don't need all those fonts, only Source Sans Pro 400, 600, 700. Make sure your editors reads the `.editorconfig` file properly, because there are several formatting problems.

2016-11-08 09:25 UTC, davidknezic commented on Jenkinsfile
> +    def baseUrl = '/' + tagName.replaceAll("[.:_/\\\\]", '-')
Isn't this going to break the `master` build, that would now have a baseUrl `/latest` instead of `/toolkit`?

2016-11-08 09:25 UTC, davidknezic commented on tests/compare.js
> +resultPage.createResultPage(pages)
Could you rewrite this to ES6?
Also make sure the `.eslintrc.json` file is correctly loaded in your editor. 
Making sure your editor reads the `.editorconfig` file will prevent those missing end lines in all your files.

2016-11-08 09:25 UTC, davidknezic commented on tests/package.json
> +  "main": "test2.js",
That file doesn't exist.

2016-11-08 09:25 UTC, davidknezic commented on tests/readme.md
> +screenshots and compare them with expected values respecitely.
> respecitely

2016-11-08 09:25 UTC, davidknezic commented on tests/template.hbs
> +            u fucked up!
Watch out for wording here.

2016-11-09 16:03 UTC, elessar-ch commented
Currently working on making this thing a bit cooler :P

2016-11-09 23:24 UTC, elessar-ch commented
Allright, I think we're close to merging now.
- Moved to ES6
- Doing the snapshots now in node too (with PhantomJS Node bridge)
- Improved result page with some colors (don't get too excited)
- Removed PT Serif
- Fixed typos in readme :P and extended it a bit

2016-11-11 10:33 UTC, davidknezic requested changes
Just three things
- `docker-compose.yml` and `font-test.hbs` still have no newlines
  
  ![screen shot 2016-11-11 at 11 30 01](https://cloud.githubusercontent.com/assets/198988/20212231/4d94266a-a802-11e6-9919-a24476d640f8.png)
- You can remove three more fonts, because we don't use italics anywhere (and hopefully never will)
  - SourceSansPro-BoldIt.ttf
  - SourceSansPro-It.ttf
  - SourceSansPro-SemiboldIt.ttf
- And I'd prefer if the `tests/readme.md` filename was capsed `README.md`.

Everything else, amazing! 🎉

2016-11-11 17:42 UTC, elessar-ch commented
@davidknezic fixed

2016-11-11 23:03 UTC, davidknezic approved these changes
👍

2016-11-11 23:04 UTC, merged