link to gh releases page
axa-group/web-toolkit pull request #63
Opened 2016-11-15 19:27 UTC by sventschui

Link to GH Releases page from Mfrom menu and from version tag

2016-11-15 19:36 UTC, FKSI commented
Oh just notice that we can use yarn the web-toolkit 😱👍 thanks @sventschui

2016-11-15 21:23 UTC, sventschui commented
A lot faster than npm. But be aware that yarn suffers from some serious bugs. If you experience issues a good ol' npm install may help ;)

2016-11-16 13:40 UTC, davidknezic requested changes

2016-11-16 13:40 UTC, davidknezic commented on docs/_partials/page.hbs
> +            <a class="label label-primary" href="https://github.com/axa-group/web-toolkit/releases" >{{package.version}}</a>
Could you put this URL to the package.json? You could add a new key like `releasesUrl`.

2016-11-16 13:40 UTC, davidknezic commented on docs/_partials/page.hbs
> +              href="https://github.com/axa-group/web-toolkit/releases">
When adding the URL to `package.json`, you could use it here, too.

2016-11-16 13:40 UTC, davidknezic commented on yarn.lock
> +    readable-stream "~2.0.0"
Why did the yarn file change so much?

2016-11-24 07:14 UTC, davidknezic approved these changes

2016-11-24 07:19 UTC, davidknezic commented
Check it out here:
https://design.axa.com/imrovement-link-to-gh-releases/

2016-11-24 07:25 UTC, merged

2016-11-24 07:25 UTC, davidknezic commented
Thanks @sventschui for the suggestion and your pr!

2016-11-24 07:43 UTC, sventschui commented
You're welcome