Browser not supported page
axa-group/web-toolkit pull request #68
Opened 2016-11-18 15:09 UTC by elessar-ch

This adds a browser not supported page and documentation of it.

2016-11-18 15:15 UTC, elessar-ch commented
Have a look at the page here:
https://design.axa.com/feature-browser-not-supported/getting-started/browser-not-supported/#redirect

2016-11-18 17:49 UTC, elessar-ch commented
Should we have the overlay on the toolkit as well?

2016-11-18 20:55 UTC, davidknezic requested changes
Awesome! Very good explanation and great (IE-) intro 😄  Love that it can be used as a page and an overlay.

I've requested some minor changes before we can merge.

2016-11-18 20:55 UTC, davidknezic commented on docs/getting-started/browser-not-supported/index.hbs
> +    {{/code-snippet}}
You don't have to break the indentation here

2016-11-18 20:55 UTC, davidknezic commented on docs/getting-started/browser-not-supported/index.hbs
> +description: asdf
How about?

> Notify users of old browsers to upgrade in order to enjoy your app.

2016-11-18 20:55 UTC, davidknezic commented on docs/getting-started/browser-not-supported/index.hbs
> +          <!--[if lte IE 9]><meta http-equiv="refresh" content="0; URL=/your/browser-not-supported-page.html"><![endif]-->
Detail, but by breaking this, you get shorter lines in the example:

```html
<!--[if lte IE 9]>
  <meta http-equiv="refresh" content="0; URL=/your/browser-not-supported-page.html">
<![endif]-->
```

2016-11-18 20:55 UTC, davidknezic commented on docs/getting-started/browser-not-supported/index.hbs
> +          Meta Tags here.
Just for copy-pasta's sake, I'd make this a comment. Also it gets highlighted in a more subtle way if it's a comment, showing users that it's only informational.

```
<!-- Meta Tags here. -->
```

2016-11-18 20:55 UTC, davidknezic commented on scss/style/_browser-not-supported.scss
> +  z-index: 999;
Can you create a z-index variable for this one?

2016-11-18 20:55 UTC, davidknezic commented on docs/getting-started/browser-not-supported/snippets/overlay.hbs
> +      <div class="jumbotron">
Wondering if you could put the `container` into the `jumbotron`, so the blue background is full-width, like our other designs?

2016-11-18 21:46 UTC, davidknezic commented
Just noticed this weird behavior...

![img_2051](https://cloud.githubusercontent.com/assets/198988/20447702/b030bdae-ade0-11e6-963d-a5c3561aa144.PNG)

2016-11-21 13:06 UTC, elessar-ch commented
Oki, fixed these issues @davidknezic.

2016-11-21 16:03 UTC, davidknezic approved these changes

2016-11-21 16:03 UTC, merged