Sassdoc pages will no longer appear in the menu twice
axa-group/web-toolkit pull request #8
Opened 2016-10-13 16:21 UTC by elessar-ch

Fixes #7

2016-10-14 05:39 UTC, davidknezic requested changes

2016-10-14 05:39 UTC, davidknezic commented on lib/metalsmith-sitemap.js
> +    // }
how comes this is commented? should we remove this?

2016-10-14 05:39 UTC, davidknezic commented on docs/wooooo.hbs
>    {{#*inline "title"}}{{title}}{{/inline}}
what is what `woooo` page anyways? do we need that?

2016-10-14 05:39 UTC, davidknezic commented on docs/components/wooooooooo.hbs
>    {{#*inline "title"}}{{title}}{{/inline}}
could we remove this page?

2016-10-14 09:44 UTC, elessar-ch commented on docs/wooooo.hbs
>    {{#*inline "title"}}{{title}}{{/inline}}
That's currently the only page showing how to include a snippet and a demo in a handlebars page

2016-10-14 09:44 UTC, elessar-ch commented on docs/components/wooooooooo.hbs
>    {{#*inline "title"}}{{title}}{{/inline}}
Will do

2016-10-14 09:45 UTC, elessar-ch commented on lib/metalsmith-sitemap.js
> +    // }
Will do

2016-10-14 09:59 UTC, elessar-ch commented
Have a look again @davidknezic

2016-10-16 21:04 UTC, davidknezic approved these changes

2016-10-16 21:05 UTC, merged